"""Blindspot v2.0 — Docx Redline Generator

Creates a .docx file with tracked-change-style annotations
showing the original text and proposed rewrites.
"""

import os
from typing import List, Dict
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from src.state.schema import Clause, Rewrite


class DocxRedliner:
    """Generates redlined .docx with proposed changes."""

    def create_redline(
        self,
        clauses: List[Clause],
        rewrites: Dict[str, Rewrite],
        output_path: str = "./generated/redlined_contract.docx"
    ) -> str:
        """Create a .docx with tracked changes showing rewrites."""

        # Ensure output directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        doc = Document()

        # Add header
        heading = doc.add_heading('Redlined Contract — Blindspot Analysis', 0)
        doc.add_paragraph(f'Generated on: Auto-generated by Blindspot v2.0')
        doc.add_paragraph('')

        # Add each clause with redlining
        for clause in clauses:
            rewrite = rewrites.get(clause.id)

            # Clause header
            if clause.section_header:
                doc.add_heading(clause.section_header, level=2)

            # Original text (strikethrough)
            para = doc.add_paragraph()
            run = para.add_run('ORIGINAL: ')
            run.bold = True
            run.font.color.rgb = RGBColor(255, 0, 0)

            original_run = para.add_run(clause.text[:500])
            original_run.font.strike = True
            original_run.font.color.rgb = RGBColor(255, 0, 0)

            # Proposed text (underline, green)
            if rewrite and rewrite.proposed_text != clause.text:
                para = doc.add_paragraph()
                run = para.add_run('PROPOSED: ')
                run.bold = True
                run.font.color.rgb = RGBColor(0, 128, 0)

                proposed_run = para.add_run(rewrite.proposed_text[:500])
                proposed_run.font.underline = True
                proposed_run.font.color.rgb = RGBColor(0, 128, 0)

                # Rationale
                ratio_para = doc.add_paragraph()
                ratio_run = ratio_para.add_run(f'Rationale: {rewrite.rationale}')
                ratio_run.italic = True
                ratio_run.font.size = Pt(9)

            doc.add_paragraph('')

        # Save
        doc.save(output_path)
        return output_path

    def create_from_text(
        self,
        original_text: str,
        rewrites_dict: Dict[str, str],
        output_path: str = "./generated/redlined_contract.docx"
    ) -> str:
        """Simple text-based redline generation."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        doc = Document()
        doc.add_heading('Contract with Proposed Changes', 0)

        # Simple approach: show original + proposed side by side
        para = doc.add_paragraph()
        para.add_run('Original Contract:\n').bold = True
        para.add_run(original_text[:2000])

        doc.add_paragraph('')
        para = doc.add_paragraph()
        para.add_run('Proposed Rewrites:\n').bold = True

        for clause_id, proposed_text in rewrites_dict.items():
            para = doc.add_paragraph()
            para.add_run(f'{clause_id}:\n').bold = True
            para.add_run(proposed_text[:500])

        doc.save(output_path)
        return output_path
